Repository miketvo/rmit-isys2099-group9-app, pull requests merged in 2023-08, with the labels that each got.

#12 Feature Users and Roles
  README.md
  database/mysql/init/mock_data.sql
  database/mysql/init/tables.sql
  database/mysql/init/users.sql
Labels: enhancement

#15 Feature MySQL business rules
  README.md
  database/mysql/init/business_rules.sql
  database/mysql/init/mock_data.sql
  database/mysql/init/tables.sql
  database/mysql/init/users.sql
  database/mysql/reset.sql
Labels: enhancement

#24 Feature MySQL business logic
  README.md
  database/mysql/init/business_rules.sql
  database/mysql/init/mock_data.sql
  database/mysql/init/tables.sql
  database/mysql/init/users.sql
  server/app.js
  server/package-lock.json
  server/package.json
Labels: documentation, enhancement

#26 Feature client mall components
  client-mall/index.html
  client-mall/package-lock.json
  client-mall/package.json
  client-mall/src/App.jsx
  client-mall/src/components/HomePage/HomePage.jsx
  client-mall/src/components/HomePage/Product/ProductCard.jsx
  client-mall/src/components/HomePage/Product/ProductList.jsx
  client-mall/src/components/Login/Login.jsx
  client-mall/src/components/NavBar/NavBar.jsx
  client-mall/src/components/Register/Register.jsx
  client-mall/src/customRouter/PageRender.jsx
  client-mall/src/customRouter/PrivateRouter.jsx
  client-mall/src/index.jsx
  client-mall/src/pages/login.jsx
  client-mall/src/pages/product/[id].jsx
  client-mall/src/pages/register.jsx
  client-mall/src/styles/global.css
  client-mall/src/utils/IconSettings.jsx
  client-mall/src/utils/config.jsx
  client-whadmin/package-lock.json
  client-whadmin/package.json
  client-whadmin/src/App.jsx
  client-whadmin/src/components/HomePage/Homepage.jsx
  client-whadmin/src/components/Login/Login.jsx
  client-whadmin/src/components/NavBar/NavBar.jsx
  client-whadmin/src/components/Register/Register.jsx
  client-whadmin/src/customRouter/PageRender.jsx
  client-whadmin/src/customRouter/PrivateRouter.jsx
  client-whadmin/src/index.jsx
  client-whadmin/src/pages/login.jsx
  client-whadmin/src/pages/product/[id].jsx
  client-whadmin/src/pages/register.jsx
  client-whadmin/src/styles/global.css
  client-whadmin/src/utils/IconSettings.jsx
  client-whadmin/src/utils/config.jsx
Labels: documentation, enhancement

#36 Feature MySQL Database NodeJS setup script
  README.md
  database/mysql/.eslintrc.json
  database/mysql/.prettierignore
  database/mysql/.prettierrc
  database/mysql/package-lock.json
  database/mysql/package.json
  database/mysql/setup.js
Labels: documentation, enhancement

#39 Feature database MongoDB setup scripts
  README.md
  client-whadmin/.eslintrc.cjs
  client-whadmin/index.html
  client-whadmin/src/index.jsx
  client-whadmin/vite.config.js
  database/mongodb/.eslintrc.json
  database/mongodb/.gitkeep
  database/mongodb/.prettierignore
  database/mongodb/.prettierrc
  database/mongodb/collections.js
  database/mongodb/mockData.js
  database/mongodb/package-lock.json
  database/mongodb/package.json
  database/mongodb/schemas.js
  database/mongodb/setup.js
  database/mysql/init/mock_data.sql
  database/mysql/init/tables.sql
  database/mysql/setup.js
  server/package.json
Labels: enhancement, help wanted

#40 Feature jwt auth
  .gitignore
  client-mall/package-lock.json
  client-mall/package.json
  client-mall/src/App.jsx
  client-mall/src/components/HomePage/Product/ProductList.jsx
  client-mall/src/components/Register/Register.jsx
  client-whadmin/.eslintrc.cjs
  client-whadmin/package-lock.json
  client-whadmin/package.json
  client-whadmin/src/App.jsx
  client-whadmin/vite.config.js
  database/mysql/init/mock_data.sql
  database/mysql/init/tables.sql
  server/.env
  server/apiRouter.js
  server/app.js
  server/models/db.js
  server/models/index.js
  server/models/model.js
  server/package-lock.json
  server/package.json
  server/server.js
  server/utils/generateTokens.js
  server/utils/index.js
  server/utils/setTokenCookie.js
  server/utils/verifyToken.js
Labels: documentation, enhancement, help wanted, question

#45 update WareHouseComponent
  client-whadmin/src/components/WareHouse/WareHouseComponent.jsx
Labels: duplicate, enhancement

#46 Fix jwt insertion and /login route
  database/mysql/init/mock_data.sql
  database/mysql/init/tables.sql
  server/apiRouter.js
  server/models/model.js
  server/utils/generateTokens.js
  server/utils/setTokenCookie.js
Labels: bug, documentation, enhancement

#48 Feature: client-mall Auth Pages and Seller Dash
  client-mall/src/App.jsx
  client-mall/src/api/fetchAPI.jsx
  client-mall/src/components/Dashboard/Items/InboundOrder.jsx
  client-mall/src/components/Dashboard/Items/Product.jsx
  client-mall/src/components/Dashboard/Layout.jsx
  client-mall/src/components/Dashboard/NavBar.jsx
  client-mall/src/components/Dashboard/PopUp/InboundOrder.jsx
  client-mall/src/components/Dashboard/PopUp/PopUp.jsx
  client-mall/src/components/Dashboard/PopUp/Product.jsx
  client-mall/src/components/Dashboard/SellerDashboardComponent.jsx
  client-mall/src/components/HomePage/Product/ProductList.jsx
  client-mall/src/components/Login/Login.jsx
  client-mall/src/components/Register/Register.jsx
  client-mall/src/images/lazada.jpg
  client-mall/src/images/potato.jpg
  client-mall/src/pages/sellerDashboard.jsx
  client-mall/src/styles/components/LoginRegister.css
  client-mall/src/styles/components/NavBar.css
  client-mall/src/styles/components/PopUp/PopUp.css
  client-mall/src/styles/components/SellerDashboard/NavBar.css
  client-mall/src/styles/components/SellerDashboard/SellerDashboard.css
  client-mall/src/styles/global.css
Labels: enhancement, help wanted
